# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'TODO-LISTs',
                'verbose_name': 'TODO-LIST',
            },
        ),
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='Description')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todolist.TodoList')),
            ],
            options={
                'verbose_name_plural': 'TODO-LIST Items',
                'verbose_name': 'TODO-LIST Item',
            },
        ),
    ]
