# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20170704_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='background_color',
            field=models.CharField(blank=True, default='ffffff', max_length=20, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='label',
            name='foreground_color',
            field=models.CharField(blank=True, default='000000', max_length=20, verbose_name='Foreground Color'),
        ),
    ]
