# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20170704_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='display_name',
            field=models.CharField(default='-', max_length=20, verbose_name='Display Name'),
            preserve_default=False,
        ),
    ]
