# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_label_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='display_name',
        ),
    ]
